[package]
name = "liteflow-testcase-el-script-qlexpress-vernal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
liteflow-core = { path = "../../liteflow-core" }
liteflow-script-qlexpress = { path = "../../liteflow-script-plugin/liteflow-script-qlexpress" }
liteflow-vernal = { path = "../../liteflow-vernal" }
