[package]
name = "liteflow-rule-nacos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Nacos rule source for liteflow-rust"

[dependencies]
liteflow-core = { path = "../../liteflow-core" }
async-trait.workspace = true
nacos-sdk.workspace = true
tokio.workspace = true
