[package]
name = "liteflow-rule-redis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Redis rule source for liteflow-rust"

[dependencies]
liteflow-core = { path = "../../liteflow-core" }
async-trait.workspace = true
redis = { workspace = true, features = ["tokio-comp", "cluster", "sentinel"] }
tokio.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
